name: Terraform - Benchmark Network Security Rule
on: 
  push:
    branches:
      - main
    paths:
        - terraform/**      
jobs:
  build:
    name: Terraform - Benchmark Network Security Rule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: | 
          # Parse Azure secret into Terraform variables
          echo "ARM_CLIENT_ID=$( jq -r '.clientId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_CLIENT_SECRET=$( jq -r '.clientSecret' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_SUBSCRIPTION_ID=$( jq -r '.subscriptionId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_TENANT_ID=$( jq -r '.tenantId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV
        shell: bash          

      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform/network_security_rule init

      - name: Initial Cleanup
        id: cleanup
        run: terraform -chdir=terraform/network_security_rule destroy -auto-approve -no-color        

      - name: Terraform Plan 200 Rules
        id: plan-200-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules-200.csv' -no-color

      - name: Terraform Apply 200 Rules
        id: apply-200-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules-200.csv' -auto-approve -no-color

      - name: Cleanup 200 Rules
        id: cleanup-200-rules
        run: terraform -chdir=terraform/network_security_rule destroy -auto-approve -no-color        

      - name: Terraform Plan 500 Rules
        id: plan-500-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules-500.csv' -no-color

      - name: Terraform Apply 500 Rules
        id: apply-500-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules-500.csv' -auto-approve -no-color

      - name: Cleanup 500 Rules
        id: cleanup-500-rules
        run: terraform -chdir=terraform/network_security_rule destroy -auto-approve -no-color     

      - name: Terraform Plan 1000 Rules
        id: plan-1000-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules-1000.csv' -no-color

      - name: Terraform Apply 1000 Rules
        id: apply-1000-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules-1000.csv' -auto-approve -no-color

      - name: Cleanup 1000 Rules
        id: cleanup-1000-rules
        run: terraform -chdir=terraform/network_security_rule destroy -auto-approve -no-color

      - name: Terraform Plan 2 Rules
        id: update-plan-2-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules.csv' -no-color        
        
      - name: Terraform Apply 2 Rules
        id: update-apply-2-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules.csv' -auto-approve -no-color

      - name: Terraform Plan Update 2 to 200 Rules
        id: update-plan-200-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules-200.csv' -no-color        
        
      - name: Terraform Apply Update 2 to 200 Rules
        id: update-apply-200-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules-200.csv' -auto-approve -no-color

      - name: Terraform Plan Update 200 to 500 Rules
        id: update-plan-500-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules-500.csv' -no-color              
        
      - name: Terraform Update 200 to 500 Rules
        id: update-apply-500-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules-500.csv' -auto-approve -no-color  
        
      - name: Terraform Plan Update 500 to 1000 Rules
        id: update-plan-1000-rules
        run: terraform -chdir=terraform/network_security_rule plan -var='rules_file=../rules-1000.csv' -no-color          

      - name: Terraform Update 500 to 1000 Rules
        id: update-apply-1000-rules
        run: terraform -chdir=terraform/network_security_rule apply -var='rules_file=../rules-1000.csv' -auto-approve -no-color     

