name: Bicep - Benchmark Network Security Rule
on: 
  push:
    branches:
      - main
    paths:
      - bicep/**
jobs:
  build:
    name: Bicep - Benchmark Network Security Rule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: | 
          # Parse Azure secret into Terraform variables
          echo "ARM_CLIENT_ID=$( jq -r '.clientId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_CLIENT_SECRET=$( jq -r '.clientSecret' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_SUBSCRIPTION_ID=$( jq -r '.subscriptionId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV;
          echo "ARM_TENANT_ID=$( jq -r '.tenantId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV
        shell: bash          

      - name: Initial Cleanup
        id: cleanup
        run: |
          if $(az group exists --name rg-bicep-networkSecurityRules) ; then
            az group delete --name rg-bicep-networkSecurityRules --yes
          fi
        shell: bash

      - name: Bicep What-if 200 Rules
        id: what-if-200-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main-200.bicep
        working-directory: ./bicep/securityRules

      - name: Bicep Create 200 Rules
        id: create-200-rules
        run: az deployment sub create --name rule --location westeurope --template-file main-200.bicep
        working-directory: ./bicep/securityRules

      - name: Cleanup 200 Rules
        id: cleanup-200-rules
        run: az group delete --name rg-bicep-networkSecurityRules --yes

      - name: Bicep What-if 500 Rules
        id: what-if-500-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main-500.bicep
        working-directory: ./bicep/securityRules

      - name: Bicep Create 500 Rules
        id: create-500-rules
        run: az deployment sub create --name rule --location westeurope --template-file main-500.bicep
        working-directory: ./bicep/securityRules

      - name: Cleanup 500 Rules
        id: cleanup-500-rules
        run: az group delete --name rg-bicep-networkSecurityRules --yes

      - name: Bicep What-if 1000 Rules
        id: what-if-1000-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main-1000.bicep
        working-directory: ./bicep/securityRules

      - name: Bicep Create 1000 Rules
        id: create-1000-rules
        run: az deployment sub create --name rule --location westeurope --template-file main-1000.bicep
        working-directory: ./bicep/securityRules

      - name: Cleanup 1000 Rules
        id: cleanup-1000-rules
        run: az group delete --name rg-bicep-networkSecurityRules --yes         

      - name: Bicep Plan 2 Rules
        id: update-what-if-2-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main.bicep
        working-directory: ./bicep/securityRules   
        
      - name: Bicep Apply 2 Rules
        id: update-create-2-rules
        run: az deployment sub create --name rule --location westeurope --template-file main.bicep
        working-directory: ./bicep/securityRules

      - name: Bicep Plan Update 2 to 200 Rules
        id: update-what-if-200-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main-200.bicep
        working-directory: ./bicep/securityRules     
        
      - name: Bicep Apply Update 2 to 200 Rules
        id: update-create-200-rules
        run: az deployment sub create --name rule --location westeurope --template-file main-200.bicep
        working-directory: ./bicep/securityRules     

      - name: Bicep Plan Update 200 to 500 Rules
        id: update-what-if-500-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main-500.bicep
        working-directory: ./bicep/securityRules        
        
      - name: Bicep Update 200 to 500 Rules
        id: update-create-500-rules
        run: az deployment sub create --name rule --location westeurope --template-file main-500.bicep
        working-directory: ./bicep/securityRules
        
      - name: Bicep Plan Update 500 to 1000 Rules
        id: update-what-if-1000-rules
        run: az deployment sub what-if --name rule --location westeurope --template-file main-1000.bicep
        working-directory: ./bicep/securityRules       

      - name: Bicep Update 500 to 1000 Rules
        id: update-create-1000-rules
        run: az deployment sub create --name rule --location westeurope --template-file main-1000.bicep
        working-directory: ./bicep/securityRules
